// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC34IdnF8COoqRm3_p1mr07sbGRXRAX3RQ',
    appId: '1:953425073032:web:2e39953a9275545bf3203d',
    messagingSenderId: '953425073032',
    projectId: 'myblog-455b9',
    authDomain: 'myblog-455b9.firebaseapp.com',
    storageBucket: 'myblog-455b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Z3SALoKr6LlE8zhlUvaWRY7bJxdiXec',
    appId: '1:953425073032:android:a2b51c45bde716b0f3203d',
    messagingSenderId: '953425073032',
    projectId: 'myblog-455b9',
    storageBucket: 'myblog-455b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ko7qBQlGjDSyWDrWDcFfB2JFSNJB75U',
    appId: '1:953425073032:ios:5371f13ec6db63a0f3203d',
    messagingSenderId: '953425073032',
    projectId: 'myblog-455b9',
    storageBucket: 'myblog-455b9.appspot.com',
    iosClientId: '953425073032-8bk70at2ldovi7b1mqbcl0n6b16r5n11.apps.googleusercontent.com',
    iosBundleId: 'com.myblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ko7qBQlGjDSyWDrWDcFfB2JFSNJB75U',
    appId: '1:953425073032:ios:5371f13ec6db63a0f3203d',
    messagingSenderId: '953425073032',
    projectId: 'myblog-455b9',
    storageBucket: 'myblog-455b9.appspot.com',
    iosClientId: '953425073032-8bk70at2ldovi7b1mqbcl0n6b16r5n11.apps.googleusercontent.com',
    iosBundleId: 'com.myblog',
  );
}
